name: db

channels:
  - defaults
  - anaconda
  - conda-forge
  - pytorch

dependencies:
  - black
  - doit
  - flake8
  - flask
  - isort
  - lightgbm
  - numpy>=1.20 # numpy.typing.
  - pandarallel # Forecast. Parallelize pandas computations.
  - pandas
  - pathlib
  - plumbum
  - psycopg2
  - psutil
  - pyarrow # Forecast. Parquet support.
  - pydotplus
  - pylint
  - pyyaml
  - scikit-learn>=1.0.0 # Behavior models.
  - setproctitle
  - pytorch==1.2.0
  - toml
  - tqdm
  - types-PyYAML
  - python=3.7
  - codecov
