import copy
import json
import logging
import pickle
import time
import os

from .algorithms.anytime_algorithm import AnytimeAlgorithm
from .algorithms.auto_admin_algorithm import AutoAdminAlgorithm
from .algorithms.db2advis_algorithm import DB2AdvisAlgorithm
from .algorithms.dexter_algorithm import DexterAlgorithm
from .algorithms.drop_heuristic_algorithm import DropHeuristicAlgorithm
from .algorithms.extend_algorithm import ExtendAlgorithm
from .algorithms.relaxation_algorithm import RelaxationAlgorithm
from .benchmark import Benchmark
from .dbms.postgres_dbms import PostgresDatabaseConnector
from .selection_algorithm import AllIndexesAlgorithm, NoIndexAlgorithm
from .workload_generator import WorkloadGenerator


ALGORITHMS = {
    "anytime": AnytimeAlgorithm,
    "auto_admin": AutoAdminAlgorithm,
    "db2advis": DB2AdvisAlgorithm,
    "dexter": DexterAlgorithm,
    "drop": DropHeuristicAlgorithm,
    "extend": ExtendAlgorithm,
    "relaxation": RelaxationAlgorithm,
    "no_index": NoIndexAlgorithm,
    "all_indexes": AllIndexesAlgorithm,
}

DEFAULT_DB = "project1db"
DEFAULT_USER = "project1user"
DEFAULT_PASS = "project1pass"
CONFIG_PATH = "./indexjungle.json"


class IndexSelection:
    def __init__(self, workload_csv_path, data_collection=False, log_level=None, disable_output_files=True):
        if "CRITICAL_LOG" == log_level:
            logging.getLogger().setLevel(logging.CRITICAL)
        if "ERROR_LOG" == log_level:
            logging.getLogger().setLevel(logging.ERROR)
        if "INFO_LOG" == log_level:
            logging.getLogger().setLevel(logging.INFO)

        # Disable output files generated by benchmark class
        self.disable_output_files = disable_output_files

        logging.debug("Init IndexSelection")
        self.db_connector = None
        self.workload = None
        self.db_name = DEFAULT_DB
        self.db_user = DEFAULT_USER
        self.db_pass = DEFAULT_PASS
        self.workload_csv_path = workload_csv_path
        # Whether indexes generated from previous iterations are reused
        self.data_collection = data_collection

        # TODO: Add other paths
        self.workload_name = "epinions"
        sample_size = 1000
        self.config_file = CONFIG_PATH
        if "epinions" in workload_csv_path:
            self.workload_name = "epinions"
            sample_size = 1000 if not data_collection else 10000
            self.config_file = "./epinions.json"
        elif "indexjungle" in workload_csv_path:
            self.workload_name = "indexjungle"
            sample_size = 1000 if not data_collection else 10000
            self.config_file = "./indexjungle.json"
        elif "timeseries" in workload_csv_path:
            self.workload_name = "timeseries"
            sample_size = 1000 if not data_collection else 10000
            self.config_file = "./timeseries.json"
        self.workload_name = "epinions"  # TODO: REMOVE
        sample_size = 1000

        self.setup_db_connector()

        # Set up Workload generator which reads workload_csv
        self.workload_generator = WorkloadGenerator(
            self.workload_csv_path, self.workload_name, self.db_connector, sample_size=sample_size)

        print(f"Running on benchmark {self.workload_name}...")

    def run(self, debug=False):
        if debug:
            logging.getLogger().setLevel(logging.DEBUG)
        logging.info("Starting Index Selection Evaluation")

        # Try to load saved indexes pickle file
        indexes = self.load_most_recent_indexes()
        if indexes == None:
            # Generate indexes if none found
            new_index = self._run_algorithms(0)
            self.save_indexes([new_index])
            self.write_actions_sql_file(
                new_index[3])
            self.print_indexes([new_index])
            return

        # Only collect goodput if data_collection flag is True
        grading_goodput = -1
        if self.data_collection:
            grading_goodput = self.load_most_recent_grading_result()
            if grading_goodput == None:
                # Generate indexes if none found
                new_index = self._run_algorithms(0)
                self.save_indexes([new_index])
                self.write_actions_sql_file(
                    new_index[3])
                self.print_indexes([new_index])
                return

        # Update goodput of latest index
        if indexes[-1] != -1:
            indexes[-1] = list(indexes[-1])
            indexes[-1][4] = grading_goodput

        # Benchmark next index
        iteration = len(indexes)
        new_index = self._run_algorithms(iteration)

        # No more indexes to benchmark, None is returned
        if new_index == None:
            self.print_indexes(indexes)
            return

        self.save_indexes(indexes + [new_index])
        self.write_actions_sql_file(
            new_index[3])
        self.print_indexes(indexes + [new_index])

    def _run_algorithms(self, config_index):
        with open(self.config_file) as f:
            config = json.load(f)
        # Initialize postgres connector
        self.setup_db_connector()
        # Enable hypopg
        self.db_connector.enable_simulation()
        # Show current indexes
        self.db_connector.show_curr_indexes()
        # Write actions to drop all indexes before dropping them
        self.write_drop_actions_sql_file()
        # Drop indexes
        self.db_connector.drop_indexes()

        # Set the random seed to obtain deterministic statistics (and cost estimations)
        # because ANALYZE (and alike) use sampling for large tables
        self.db_connector.create_statistics()
        self.db_connector.commit()

        # 'config_index' tells us which config and which parameter should be run next.
        # First calculate the correponding algo based on config_index, then run that algo
        # If all configs have been used, loop back to runthe first config again
        number_of_actual_runs = config[
            "number_of_actual_runs"] if "number_of_actual_runs" in config else 0
        total_configs = config["number_of_total_configs"]
        config_index = config_index % total_configs

        algorithm_config = None
        cumulative_config_index = 0
        for algorithm_config in config["algorithms"]:
            # There are multiple configs if there is a parameter list
            # configured (as a list in the .json file)
            algorithm_config["number_of_actual_runs"] = number_of_actual_runs
            configs = self._find_parameter_list(algorithm_config)

            if config_index < cumulative_config_index + len(configs):
                algorithm_config = configs[config_index -
                                           cumulative_config_index]
                break  # Algorithm found
            else:
                cumulative_config_index += len(configs)
        if algorithm_config == None:
            return None

        print(
            f"Setup complete!\nStart running {algorithm_config['name']} with {algorithm_config['parameters']}...")

        algo_start_time = time.time()
        # Generate new sample workload of sample_size=x
        self.workload = self.workload_generator.generate_sample_workload()
        cfg = algorithm_config
        indexes, what_if, cost_requests, cache_hits = self._run_algorithm(
            cfg)

        calculation_time = round(time.time() - algo_start_time, 2)
        benchmark = Benchmark(
            self.workload,
            indexes,
            self.db_connector,
            cfg,
            calculation_time,
            self.disable_output_files,
            config,
            cost_requests,
            cache_hits,
            what_if,
        )

        cost, _, _ = benchmark.benchmark()

        # The last element is goodput which will be obtained from the grading script later
        best_indexes = [
            algorithm_config["name"], cfg["parameters"], cost, indexes, calculation_time, -1]
        algo_time = round(time.time() - algo_start_time, 2)
        print(
            f"{algorithm_config['name']} finished in {algo_time} seconds...")

        return best_indexes

    @staticmethod
    def print_indexes(best_indexes):
        for name, parameters, cost, indexes, _, goodput in best_indexes:
            print(
                f"====== {name}, goodput:{goodput:.4f}, cost: {cost:.4f}, params: {parameters}, Indexes: {indexes}\n")

    def save_indexes(self, indexes):
        save_dir = os.path.join(os.getcwd(), f"indexes_results/")
        if not os.path.exists(save_dir):
            os.makedirs(save_dir)

        filepath = os.path.join(
            save_dir, f"{self.workload_name}.pickle")

        with open(filepath, "wb") as file:
            print(f'Saving index to {filepath}...')
            pickle.dump(indexes, file)

    def load_most_recent_grading_result(self):
        save_dir = os.path.join(os.getcwd(), f"grading/")
        if not os.path.exists(save_dir):
            return None

        dir_names = os.listdir(save_dir)
        dir_names = sorted([
            dir_name for dir_name in dir_names if 'baseline' not in dir_name],
            key=lambda x: int(x.rsplit('_', 1)[1]),
            reverse=True)

        if len(dir_names) == 0:
            return None

        for dir_name in dir_names:
            iter_dir_name = os.path.join(save_dir, dir_name)
            iter_filenames = os.listdir(iter_dir_name)
            if self.workload_name not in iter_filenames[0]:
                continue
            result_filename = [
                fn for fn in iter_filenames if 'summary.json' in fn][0]

            result_filename = os.path.join(iter_dir_name, result_filename)
            print(f"loading results from {result_filename}...")
            with open(result_filename) as f:
                result_json = json.load(f)
                return result_json["Goodput (requests/second)"]

        return None

    def load_most_recent_indexes(self):
        save_dir = os.path.join(os.getcwd(), f"indexes_results/")
        if not os.path.exists(save_dir):
            return None

        filenames = os.listdir(save_dir)

        most_recent_filenames = sorted([
            filename for filename in filenames if self.workload_name in filename], reverse=True)

        if len(most_recent_filenames) == 0:
            return None

        most_recent_filename = most_recent_filenames[0]
        print(f"loading indexes from {most_recent_filename}...")
        with open(os.path.join(save_dir, most_recent_filename), "rb") as file:
            indexes = list(pickle.load(file))

        return indexes

    def write_drop_actions_sql_file(self):
        with open('./actions.sql', 'w') as file:
            # Drop all old indexes, excluding UNIQUE ones
            drop_indexes = self.db_connector.get_indexes_to_drop()
            for index_name, index_df in drop_indexes:
                # Ignore PRIMARY KEY or UNIQUE indexes
                if 'UNIQUE' in index_df:
                    continue
                drop_stmt = "drop index {};".format(index_name)
                file.write(drop_stmt)
                file.write('\n')

    def write_actions_sql_file(self, indexes: list) -> list:
        print("Generating actions.sql...")
        with open('./actions.sql', 'w') as file:
            # Write create index statements
            for i, index in enumerate(indexes):
                table_name = index.table()
                stmt = (
                    f"create index {index.index_idx()} "
                    f"on {table_name} ({index.joined_column_names()});"
                )
                file.write(stmt)
                file.write('\n')

    # Parameter list example: {"max_indexes": [5, 10, 20]}
    # Creates config for each value
    def _find_parameter_list(self, algorithm_config):
        parameters = algorithm_config["parameters"]
        configs = []
        if parameters:
            # if more than one list --> raise
            self.__check_parameters(parameters)
            for key, value in parameters.items():
                if isinstance(value, list):
                    for i in value:
                        new_config = copy.deepcopy(algorithm_config)
                        new_config["parameters"][key] = i
                        configs.append(new_config)
        if len(configs) == 0:
            configs.append(algorithm_config)
        return configs

    def __check_parameters(self, parameters):
        counter = 0
        for key, value in parameters.items():
            if isinstance(value, list):
                counter += 1
        if counter > 1:
            raise Exception("Too many parameter lists in config")

    def _run_algorithm(self, config):
        self.db_connector.drop_indexes()
        self.db_connector.commit()
        self.setup_db_connector()

        algorithm = self.create_algorithm_object(
            config["name"], config["parameters"])
        logging.info(f"Running algorithm {config}")
        indexes = algorithm.calculate_best_indexes(self.workload)
        logging.info(f"Indexes found: {indexes}")
        what_if = algorithm.cost_evaluation.what_if

        cost_requests = (
            self.db_connector.cost_estimations
            if config["name"] == "db2advis"
            else algorithm.cost_evaluation.cost_requests
        )
        cache_hits = (
            0 if config["name"] == "db2advis" else algorithm.cost_evaluation.cache_hits
        )
        return indexes, what_if, cost_requests, cache_hits

    def create_algorithm_object(self, algorithm_name, parameters) -> AllIndexesAlgorithm:
        algorithm = ALGORITHMS[algorithm_name](self.db_connector, parameters)
        return algorithm

    def setup_db_connector(self):
        if self.db_connector:
            logging.info("Create new database connector (closing old)")
            self.db_connector.close()
        self.db_connector = PostgresDatabaseConnector(
            self.db_name, self.db_user, self.db_pass)
